version: 0.0
os: linux
files:
  - source: /
    destination: /opt/nodeapp
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ec2-user
